# SPDX-License-Identifier: GPL-3.0-only

[storage]
driver = "overlay"
runroot = "/var/run/containers/storage"
graphroot = "/var/lib/containers/storage"

[storage.options]
additionalimagestores = []

[storage.options.overlay]
ignore_chown_errors = "true"
mountopt = "nodev,nosuid"
